---
title: "A57_Project"
author: "Anwar, Damaj, Zhu"
date: "2025-03-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```




```{r, include = FALSE}
library(tidyverse)
library(readxl)
library(lubridate)
library(ggplot2)
library(lubridate)
library(knitr)
library(stringr)
library(tidygeocoder)
```

Load Datasets
```{r, include = FALSE}
NOX <- read_excel("./data/NOX.xlsx", skip = 3)
O3 <- read_excel("./data/O3.xlsx", skip = 3)
PM25 <- read_excel("./data/PM25.xlsx", skip = 5)
SO2 <- read_excel("./data/SO2.xlsx", , skip = 7)
```

Fix typing
```{r, include=FALSE}
NOX = NOX %>% mutate(Mean = as.numeric(Mean)) %>%  filter(Year >= 2003)
O3 = O3 %>% mutate(Mean = as.numeric(Mean)) %>%  filter(Year >= 2003)
PM25 = PM25 %>% mutate(Mean = as.numeric(Mean)) %>% mutate(Year = as.integer(Year)) %>%  filter(Year >= 2003)
SO2 = SO2 %>% mutate(Mean = as.numeric(Mean)) %>%  filter(Year >= 2003)
#view(PM25)
```

## NA imputing (TODO: decide what to do with this later)
```{r}
O3 = O3 %>% drop_na(Mean)
NOX = NOX %>% drop_na(Mean)
PM25 = PM25 %>% drop_na(Mean)
SO2 = SO2 %>% drop_na(Mean)
```

## Grouping similar regions
```{r, include = F}
excluded_cities = list(c("Chatham", "Sarnia"), 
                       c("St. Catharines", "Brantford", "Kitchener"), 
                       c("Hamilton Downtown", "Hamilton West"))

group_cities <- function(data, exclude_cities){
  grouped_data <- data %>%
  filter(!City %in% exclude_cities) %>%  
  # Exclude the cities from the dataset
  bind_rows(
    data %>%
      # Get only the two cities we want, group their year rows, get their means and turn them into one row
      filter(City %in% exclude_cities) %>%  
      group_by(Year) %>%
      # take mean of each column accross the row
      summarise(across(where(is.numeric), ~mean(.x, na.rm = TRUE)), .groups = "drop") %>%
      # fix the city name to be a combo of all cities
      mutate(City = paste(exclude_cities, collapse = "-"))
  )
  return(grouped_data)
}

for(excluded_city in excluded_cities){
  NOX <- group_cities(NOX, excluded_city)
  O3 <- group_cities(O3, excluded_city)
  PM25 <- group_cities(PM25, excluded_city)
  SO2 <- group_cities(SO2, excluded_city)
}
```

## Map cities
```{r}
NOX_LL = read_excel("./data/NOX_LL.xlsx")
NOX_LL = NOX_LL %>% filter(Longitude < -50)
NOX_map = ggplot(NOX_LL, aes(Longitude, Latitude)) + 
  geom_jitter(size=0.1) +
  coord_quickmap()
NOX_map
```


Visualizing
```{r}
#x = left_join(CO, NO2, by = join_by("Year", "City"), suffix = c(".CO", ".NO2"))
#x = left_join(x, NOX, by = year)
#x = left_join(x, PM25)
#x = left_join(x, SO2)
```


```{r}
ggplot(NOX, aes(x = Year, y = Mean, col = City)) + geom_line() + facet_wrap(~ City) + theme(legend.position="none") 
ggplot(O3, aes(x = Year, y = Mean, col = City)) + geom_point() + theme(legend.position="none") 
ggplot(PM25, aes(x = Year, y = Mean, col = City)) + geom_point() + theme(legend.position="none")
ggplot(SO2, aes(x = Year, y = Mean, col = City)) + geom_point() + theme(legend.position="none") 
```

Tables
```{r}
# Make tables
# Mean per years for that particulate matter

NOX_City_mean = NOX %>% group_by(City) %>% summarise("Mean NOX" = mean(Mean))

# kable(NOX_City_mean)

SO2_City_mean = SO2 %>% group_by(City) %>% summarise("Mean SO2" = mean(Mean))
O3_City_mean = O3 %>% group_by(City) %>% summarise("Mean O3" = mean(Mean))
PM25_City_mean = PM25 %>% group_by(City) %>% summarise("Mean PM25" = mean(Mean))

```

## Need To Decide What to do with the NAs, left_join? or smthn?
```{r}
# Making one big table of Pollutant by City 

City_Means = list(NOX_City_mean, PM25_City_mean, SO2_City_mean, O3_City_mean)

Combined_City_Mean = reduce(City_Means, full_join, by = "City")
head(kable(Combined_City_Mean))

```

```{r}
NOX_Yearly_Mean = NOX %>% group_by(Year) %>% summarise("Mean NOX" = mean(Mean))
O3_Yearly_Mean = O3 %>% group_by(Year) %>% summarise("Mean O3" = mean(Mean))
PM25_Yearly_Mean = PM25 %>% group_by(Year) %>% summarise("Mean PM25" = mean(Mean))
SO2_Yearly_Mean = SO2 %>% group_by(Year) %>% summarise("Mean SO2" = mean(Mean))



head(kable(NOX_Yearly_Mean))
```



## Same thing w NAs, we prob should na.rm when we use mean O-O
```{r}
# Making one big table of Pollutant by City 

Yearly_Means = list(NOX_Yearly_Mean, PM25_Yearly_Mean, SO2_Yearly_Mean, O3_Yearly_Mean)

Combined_Yearly_Mean = reduce(Yearly_Means, full_join, by = "Year")
head(kable(Combined_Yearly_Mean))

```


```{r}
Graphing_Yearly_Means <- Combined_Yearly_Mean %>% 
               pivot_longer(cols = starts_with("Mean"),
               names_to = "Pollutant",
               values_to = "Value")
head(kable(Graphing_Yearly_Means))
ggplot(Graphing_Yearly_Means, 
       aes(x = Year, y = Value, 
           col = factor(Pollutant, 
                        levels = c("Mean NOX", "Mean O3", "Mean PM25", "Mean SO2"), 
                        labels = c("NOX", "O3", "PM25", "SO2")))) + 
      geom_point() +
      labs(col = "Pollutants")
```

## Paired T-test
compare the value of two years (2003, 2022), x_2003, x_2022
H_0: u_1 - u_2 = 0
H_a: u_1 - u_2 != 0

```{r}
# find 2003, 2022
values.2003 = NOX %>% filter(Year == 2003) %>% select(City, Mean)
values.2022 = NOX %>% filter(Year == 2022) %>% select(City, Mean)
values = left_join(values.2003, values.2022, by="City")
values = values %>% mutate(diff = Mean.x - Mean.y)
t.test(values$diff)
```
```{r}
# find 2003, 2022
values.2003 = O3 %>% filter(Year == 2003) %>% select(City, Mean)
values.2022 = O3 %>% filter(Year == 2022) %>% select(City, Mean)
values = left_join(values.2003, values.2022, by="City")
values = values %>% mutate(diff = Mean.x - Mean.y)
t.test(values$diff)
```
```{r}
# find 2003, 2022
values.2003 = PM25 %>% filter(Year == 2003) %>% select(City, Mean)
values.2022 = PM25 %>% filter(Year == 2022) %>% select(City, Mean)
values = left_join(values.2003, values.2022, by="City")
values = values %>% mutate(diff = Mean.x - Mean.y)
t.test(values$diff)
```
```{r}
# find 2003, 2022
values.2003 = SO2 %>% filter(Year == 2003) %>% select(City, Mean)
values.2022 = SO2 %>% filter(Year == 2022) %>% select(City, Mean)
values = left_join(values.2003, values.2022, by="City")
values = values %>% mutate(diff = Mean.x - Mean.y)
t.test(values$diff)
```


